// ==UserScript==
// @name         生图助手 (Fix v30 - Direct Call)
// @version      30
// @description  移除模拟点击，改为直接调用handleGeneration()函数，提升稳定性
// @author       Walkeatround & Gemini & AI Assistant
// @match        */*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';
    console.log('[SD Helper v30] Script loaded (Direct Function Call).');

    const SCRIPT_ID = 'sd_gen_standard_v30';
    const STORAGE_KEY = 'sd_gen_settings_v30';
    const NO_GEN_FLAG = '<!--no-gen-->';
    
    const RUNTIME_LOGS = [];
    function addLog(type, msg) {
        const time = new Date().toLocaleTimeString();
        const logLine = `[${time}] [${type}] ${msg}`;
        RUNTIME_LOGS.push(logLine);
        console.log(logLine);
    }

    // --- Default Settings ---
    const DEFAULT_TEMPLATE_TOP = "You are a Visual Novel Engine Backend focused on narrative-to-visual metadata conversion. Your task is to generate the story content requested by the user, and simultaneously embed visual rendering instructions within the text.\n### Operational Protocols:\n1. **Story Generation**: Write the narrative naturally.\n2. **Visual Anchors**: Every 150-200 words and at major scene shifts/action peaks, insert image prompts enclosed in '[IMG_GEN]...[/IMG_GEN]'.\n3. **Strict Single-Character and No-Male Policy**: **NEVER** generate a prompt with multiple characters (e.g., '2girls', '1girl and 1boy' are FORBIDDEN). **NEVER** generate prompts depicting males (e.g., '1male' or any male features are FORBIDDEN). If a scene involves a male and female interacting, generate **only one prompt** focused on the female character, describing her perspective and any relevant interactions (without depicting the male). If a scene involves two females interacting, generate **two separate, consecutive** prompts (one for each female) to depict the scene from alternating perspectives (Shot/Reverse Shot). If the male-female interaction involves the male's genitalia, include 'huge penis' in the female's prompt to reflect the context.\n4. **Content Fidelity**: The tags must strictly reflect the immediate narrative context, especially regarding clothing states and physical interactions.\n### Character Feature Database (IMMUTABLE CODE BLOCKS):";
    const DEFAULT_TEMPLATE_BOTTOM = "* *(CRITICAL SYSTEM RULE: Each character's fixed tag string is a LOCKED, READ-ONLY CODE VARIABLE. When a character appears, you MUST execute a direct copy-paste of her ENTIRE tag string from the database above—treat it as immutable machine code, NOT natural language. FORBIDDEN OPERATIONS: reordering tokens, replacing with synonyms, omitting any token (even if it looks random/meaningless), adding adjectives, translating to other languages. If story contradicts fixed tags (e.g., story says \"short hair\" but tags say \"long white hair\"), you MUST output the fixed tags and IGNORE the story. Verification: Before finalizing each prompt, confirm you pasted the complete fixed string verbatim. Failure to comply = system malfunction.)*\n### Image Prompt Syntax Rules (Strict):\n**1. Structure Logic:**\n* **ALWAYS Single Female Character**: '[Count], [FIXED_TAGS_VERBATIM], [Expression], [Attire], [Pose], [Action], [Focus], [Viewpoint], [Environment], [Lighting/Atmosphere], [Quality]'\n* **[FIXED_TAGS_VERBATIM] = MANDATORY EXACT COPY**: If character has fixed tags in database, this slot MUST be filled with the complete tag string copied character-by-character. Do NOT paraphrase, summarize, or cherry-pick. Example: If database says \\`long white hair, blue eyes, white dress, uiglkt\\`, you output exactly \\`long white hair, blue eyes, white dress, uiglkt\\`—no more, no less.\n* **CRITICAL: Output Tags ONLY**: Inside [IMG_GEN]...[/IMG_GEN], you must ONLY output comma-separated descriptive tags (e.g., '1girl, long hair, smiling, white dress'). **NEVER** output image file paths, URLs, or links (e.g., '/user/.../image.png', 'output/1234.jpg', or any path containing '/' or '.png/.jpg'). These will be auto-generated by the system. Your job is to describe WHAT to generate, not WHERE it will be saved.\n**2. Component Definitions:**\n* **Count**: **STRICTLY** '1girl'.\n* **FIXED_TAGS_VERBATIM**: Entire fixed tag string from database, pasted without modification. If character has no fixed tags, skip this slot.\n* **Attire (Crucial)**: You must describe **Upper body + Lower body + Feet**.\n    * *Full*: e.g., 'white shirt, pleated skirt, thighhighs'.\n    * *Partial/Missing*: If a part is missing, use 'naked [part]' or 'bare [part]'. (e.g., 'topless', 'bare shoulders', 'bottomless', 'naked', 'barefoot', 'bare legs').\n* **Focus**: 'portrait', 'upper body', 'cowboy shot', or 'full body'.\n* **Viewpoint**: 'from below', 'from above', 'from side', 'from behind', 'from back', or 'straight-on'.\n* **Quality Suffix**: 'highly detailed, masterpiece, best quality, aesthetic, sensitive'\n### Execution Logic for Multi-Character Interactions:\n**Since simultaneous depiction is forbidden and males are prohibited, use the following techniques:**\n1. **Identify Interaction**: If Character A (male) and Character B (female) are interacting (e.g., talking, hugging, fighting, or involving genitalia).\n2. **Generate Only Female Prompt**: Focus solely on the female (Character B). Describe her action, reaction, or perspective towards the 'off-screen' male. If the interaction involves the male's genitalia, include 'huge penis' in the prompt.\n3. **For Two Females (e.g., Character B and Character C)**: Generate Prompt 1 for Character B (her action towards off-screen Character C), then immediately Prompt 2 for Character C (her reaction or reciprocal action).\n4. **Context Consistency**: Ensure the 'Environment', 'Lighting', and 'Quality' tags match exactly in paired prompts (for two-female interactions) to maintain scene continuity.\n### Example Output:\n(Narrative text...) WKR grabbed Hongryeon's hand tightly...\n[IMG_GEN]\n1girl, long white hair, blue eyes, white kimono, uiglkt, blushing, surprised, white kimono, sash, barefoot, looking up, hand being held, upper body, straight-on, warm light, highly detailed, masterpiece, best quality\n[/IMG_GEN]\n*(Note: The fixed tags 'long white hair, blue eyes, white kimono, uiglkt' were pasted verbatim from Hongryeon's database entry, regardless of story context.)*\n**Proceed with the story generation and prompt insertion now.**";

    const DEFAULT_SETTINGS = {
        enabled: true,
        startTag: '[IMG_GEN]',
        endTag: '[/IMG_GEN]',
        globalPrefix: 'best quality, masterpiece', 
        globalSuffix: '',
        globalNegative: 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry',
        injectEnabled: true,
        injectDepth: 0,
        injectRole: 'system',
        useRawMode: false, 
        injectPrompt: '',
        templateTop: DEFAULT_TEMPLATE_TOP,
        templateBottom: DEFAULT_TEMPLATE_BOTTOM,
        characters: [{ name: 'Character 1', tags: 'long white hair, blue eyes, white dress', enabled: true }],
        aiUpdateWithTemplate: false,
        llmConfig: { baseUrl: 'https://api.deepseek.com', apiKey: '', model: 'deepseek-chat', maxTokens: 4096, temperature: 0.7 }
    };

    let settings = DEFAULT_SETTINGS;
    let debounceTimer = null;
    let persistentListenCount = 0;

    // --- CSS ---
    const GLOBAL_CSS = `
    .sd-ui-container * { box-sizing: border-box; user-select: none; }
    .sd-ui-wrap {
        display: flex; flex-direction: column;
        background: transparent; border: none; margin: 5px 0;
        width: 100%; position: relative; transition: all 0.3s ease;
    }
    .sd-ui-toggle {
        text-align: center; cursor: pointer; font-size: 0.8em; opacity: 0.2;
        color: var(--SmartThemeBodyColor, #ccc); margin-bottom: 2px;
        transition: opacity 0.2s; line-height: 1;
    }
    .sd-ui-toggle:hover { opacity: 1; color: var(--SmartThemeQuoteColor, #00afff); }
    .sd-ui-viewport {
        position: relative; width: 100%; min-height: 50px;
        display: flex; align-items: center; justify-content: center;
        transition: all 0.3s ease; overflow: hidden;
    }
    .sd-ui-viewport.collapsed { display: none; }
    .sd-ui-image {
        max-width: 100%; max-height: 600px; width: auto; height: auto;
        border-radius: 6px; box-shadow: 0 4px 12px rgba(0,0,0,0.3);
        transition: opacity 0.2s;
        z-index: 1;
    }
    .sd-zone { position: absolute; background: transparent; }
    .sd-zone.delete { bottom: 0; left: 0; width: 40%; height: 5%; z-index: 100; cursor: no-drop; }
    .sd-zone.left { top: 0; left: 0; width: 20%; height: 90%; z-index: 90; cursor: w-resize; }
    .sd-zone.right { top: 0; right: 0; width: 20%; height: 90%; z-index: 90; cursor: e-resize; }
    .sd-zone.right.gen-mode { cursor: alias; }
    .sd-zone.top { top: 0; left: 0; width: 100%; height: 20%; z-index: 80; cursor: text; }
    .sd-ui-msg {
        position: absolute; bottom: 10px; left: 50%; transform: translateX(-50%);
        background: rgba(0,0,0,0.6); color: #fff; padding: 4px 8px;
        border-radius: 4px; font-size: 11px; pointer-events: none;
        opacity: 0; transition: opacity 0.3s; z-index: 15; white-space: nowrap;
    }
    .sd-ui-msg.show { opacity: 1; }
    .sd-placeholder {
        padding: 20px; border: 1px dashed rgba(255,255,255,0.1);
        border-radius: 6px; color: #aaa; font-size: 0.9em;
        text-align: center; width: 100%; opacity: 0.5;
    }
    /* Menu & Styles */
    .sd-tab-nav { display: flex; border-bottom: 1px solid var(--SmartThemeBorderColor, #555); margin-bottom: 15px; }
    .sd-tab-btn { padding: 8px 16px; cursor: pointer; opacity: 0.6; border-bottom: 2px solid transparent; font-weight: bold; }
    .sd-tab-btn:hover { opacity: 0.8; background: rgba(255,255,255,0.05); }
    .sd-tab-btn.active { opacity: 1; border-bottom-color: var(--SmartThemeQuoteColor, #00afff); color: var(--SmartThemeQuoteColor, #00afff); }
    .sd-tab-content { display: none; animation: sd-fade 0.2s; }
    .sd-tab-content.active { display: block; }
    @keyframes sd-fade { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }
    .sd-char-row { display: flex; gap: 5px; margin-bottom: 8px; align-items: flex-start; }
    .sd-char-name { flex: 0 0 25%; font-weight: bold; }
    .sd-char-tags { flex: 1; font-family: monospace; font-size: 0.9em; }
    .sd-char-del { flex: 0 0 30px; background: rgba(200,50,50,0.3); color: #fff; border: 1px solid rgba(255,255,255,0.1); cursor: pointer; height: 38px; border-radius: 3px; }
    .sd-char-del:hover { background: rgba(200,50,50,0.6); }
    .sd-add-btn { width: 100%; padding: 8px; background: rgba(255,255,255,0.1); border: 1px dashed #777; color: #ccc; cursor: pointer; margin-bottom: 15px; }
    .sd-add-btn:hover { background: rgba(255,255,255,0.15); color: #fff; border-color: #999; }
    .sd-accordion { cursor: pointer; padding: 10px; background: rgba(0,0,0,0.2); border-radius: 4px; margin-top: 10px; display: flex; justify-content: space-between; align-items: center; }
    .sd-accordion:hover { background: rgba(0,0,0,0.3); }
    .sd-accordion-content { display: none; padding-top: 10px; }
    .sd-accordion-content.show { display: block; }
    .sd-ai-update-box { margin-bottom: 10px; padding: 10px; background: rgba(0,0,0,0.2); border-radius: 5px; display: none; border-left: 2px solid var(--SmartThemeQuoteColor); }
    .sd-ai-update-box.show { display: block; animation: sd-fade 0.2s; }
    `;

    // --- UTILITIES ---
    async function fetchModels(baseUrl, apiKey) {
        try {
            let url = baseUrl.replace(/\/$/, '');
            url += '/models';
            const headers = {};
            if (apiKey) headers['Authorization'] = `Bearer ${apiKey}`;

            const res = await fetch(url, { method: 'GET', headers: headers });
            if (!res.ok) {
                const errText = await res.text();
                throw new Error(`HTTP ${res.status}: ${errText.substring(0, 100)}`);
            }
            const data = await res.json();
            return data.data || data;
        } catch (e) {
            console.error(e);
            throw new Error(e.message || '连接失败，请检查URL或API Key');
        }
    }

    async function callLLMForUpdate(prompt, instruction) {
        const config = settings.llmConfig;
        if (!config.baseUrl) throw new Error("API URL 未配置");

        const url = config.baseUrl.replace(/\/$/, '') + '/chat/completions';
        const isDeepSeek = config.baseUrl.includes('deepseek');
        
        let safeMaxTokens = parseInt(config.maxTokens) || 500;
        if (isDeepSeek && safeMaxTokens > 8192) safeMaxTokens = 8192;

        let safeModel = config.model;
        if (!safeModel && isDeepSeek) safeModel = 'deepseek-chat';
        if (!safeModel) safeModel = 'gpt-3.5-turbo';

        let userContent = `Current Prompt: ${prompt}\n\nInstruction: ${instruction}\n\nModified Prompt:`;
        let systemContent = "You are a Stable Diffusion Prompt Assistant. Your goal is to modify the User's image prompt based on their specific instructions.\nRules:\n1. Output ONLY the modified comma-separated tags.\n2. Do NOT output markdown, prefixes, explanations, or chat.\n3. Keep existing tags unless the instruction specifically contradicts them.";

        if (settings.aiUpdateWithTemplate && settings.injectPrompt) {
            userContent = `### Full Context / Character Settings (Reference Only):\n${settings.injectPrompt}\n\n---\n\n### Task:\nCurrent Prompt: ${prompt}\n\nInstruction: ${instruction}\n\nModified Prompt:`;
            systemContent += "\n\nIMPORTANT: The user may provide a full 'Context/Template' containing instructions for writing stories. IGNORE all story-writing instructions. Your ONLY job is to modify the image tags based on the 'Instruction' and the character details found in the Context.";
        }

        const messages = [
            { role: "system", content: systemContent },
            { role: "user", content: userContent }
        ];

        const payload = {
            messages: messages,
            model: safeModel,
            temperature: parseFloat(config.temperature) || 0.7,
            max_tokens: safeMaxTokens,
            stream: false
        };
        
        const headers = { "Content-Type": "application/json" };
        if (config.apiKey) headers["Authorization"] = `Bearer ${config.apiKey}`;

        const res = await fetch(url, {
            method: "POST",
            headers: headers,
            body: JSON.stringify(payload)
        });

        if (!res.ok) {
            const errText = await res.text();
            throw new Error(`API Error ${res.status}: ${errText.substring(0, 200)}`);
        }

        const data = await res.json();
        if (data.choices && data.choices.length > 0) {
            return data.choices[0].message.content.trim();
        }
        throw new Error("No response from AI");
    }

    // --- CORE API COMPATIBILITY FIX ---
    async function safeUpdateChat(messageIndex, newContent) {
        // Try modern API first
        if (typeof SillyTavern.setChatMessages === 'function') {
            try {
                await SillyTavern.setChatMessages([{
                    message_id: messageIndex,
                    message: newContent
                }], { refresh: 'affected' });
                return;
            } catch(e) {
                console.warn('[SD] setChatMessages failed, falling back to legacy method.', e);
            }
        }
        
        // Fallback for older ST or exceptions
        console.log('[SD] Using legacy chat update method.');
        if (SillyTavern.chat && SillyTavern.chat[messageIndex]) {
            SillyTavern.chat[messageIndex].mes = newContent;
            await SillyTavern.saveChat();
        }
    }

    // --- Initialization ---
    const waitForCore = setInterval(() => {
        if (typeof SillyTavern !== 'undefined' && typeof $ !== 'undefined' && SillyTavern.chat) {
            clearInterval(waitForCore);
            injectGlobalStyles(); 
            loadSettings();
            initScript();
        }
    }, 500);

    function injectGlobalStyles() {
        if ($('#sd-global-css-v30').length) return;
        $('<style id="sd-global-css-v30">').text(GLOBAL_CSS).appendTo('head');
        console.log('[SD] Global CSS injected.');
    }

    function loadSettings() {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) {
            try { 
                const parsed = JSON.parse(stored);
                settings = { ...DEFAULT_SETTINGS, ...parsed };
                if (!parsed.llmConfig) settings.llmConfig = DEFAULT_SETTINGS.llmConfig;
                else settings.llmConfig = { ...DEFAULT_SETTINGS.llmConfig, ...parsed.llmConfig };
            } 
            catch (e) { console.error(e); }
        }
    }

    function saveSettings() {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
    }

    function initScript() {
        addMenuItem();
        initGlobalListeners();
        registerSTEvents();
        setTimeout(processChatDOM, 1000);
    }

    // --- Global Event Delegation ---
    function initGlobalListeners() {
        const $chat = $('#chat');
        
        const getState = ($target) => {
            const $wrap = $target.closest('.sd-ui-wrap');
            const $mes = $wrap.closest('.mes');
            const mesId = $mes.attr('mesid');
            if (!$wrap.length || !mesId) return null;

            return {
                $wrap,
                mesId,
                prompt: decodeURIComponent($wrap.attr('data-prompt')),
                images: JSON.parse(decodeURIComponent($wrap.attr('data-images'))),
                preventAuto: $wrap.attr('data-prevent-auto') === 'true',
                blockIdx: parseInt($wrap.attr('data-block-idx')),
                el: {
                    img: $wrap.find('.sd-ui-image'),
                    msg: $wrap.find('.sd-ui-msg'),
                    viewport: $wrap.find('.sd-ui-viewport'),
                    toggle: $wrap.find('.sd-ui-toggle'),
                }
            };
        };

        $chat.on('click', '.sd-ui-toggle', function(e) {
            e.stopPropagation();
            const s = getState($(this));
            if(!s) return;
            s.el.viewport.toggleClass('collapsed');
            s.el.toggle.text(s.el.viewport.hasClass('collapsed') ? '▿' : '▵');
        });

        // LEFT NAV
        $chat.on('click', '.sd-zone.left', function(e) {
            e.stopPropagation();
            const s = getState($(this));
            if(!s) return;
            
            const rawIdx = s.$wrap.attr('data-cur-idx');
            let curIdx = (rawIdx !== undefined && rawIdx !== '') ? parseInt(rawIdx) : (s.images.length - 1);
            
            if (curIdx > 0) {
                curIdx--;
                updateWrapperView(s.$wrap, s.images, curIdx);
            }
        });

        // RIGHT NAV & GEN
        $chat.on('click', '.sd-zone.right', function(e) {
            e.stopPropagation();
            const s = getState($(this));
            if(!s) return;
            
            const rawIdx = s.$wrap.attr('data-cur-idx');
            let curIdx = (rawIdx !== undefined && rawIdx !== '') ? parseInt(rawIdx) : (s.images.length - 1);
            const count = s.images.length;

            if (curIdx < count - 1) {
                curIdx++;
                updateWrapperView(s.$wrap, s.images, curIdx);
            } else {
                addLog('CLICK_GEN', `Block ${s.blockIdx}: 用户手动点击右侧区域触发生图`);
                handleGeneration(s);
            }
        });
        
        $chat.on('click', '.sd-ui-image', function() {
            const src = $(this).attr('src');
            if(src) window.open(src, '_blank');
        });

        $chat.on('click', '.sd-zone.delete', async function(e) {
            e.stopPropagation();
            if (!confirm('确定删除这张图片吗？')) return;
            const s = getState($(this));
            if(!s) return;
            
            const rawIdx = s.$wrap.attr('data-cur-idx');
            let curIdx = (rawIdx !== undefined && rawIdx !== '') ? parseInt(rawIdx) : (s.images.length - 1);
            
            s.images.splice(curIdx, 1);
            if (s.images.length === 0) s.preventAuto = true;
            
            await updateChatData(s.mesId, s.blockIdx, s.prompt, s.images, s.preventAuto);
            updateWrapperView(s.$wrap, s.images, Math.max(0, s.images.length - 1));
        });

        $chat.on('click', '.sd-zone.top', function(e) {
            e.stopPropagation();
            const s = getState($(this));
            if(!s) return;
            openEditPopup(s);
        });
    }

    // --- Action Logic ---
    async function handleGeneration(state) {
        addLog('GEN_START', `Block ${state.blockIdx}: 开始生图流程 - Prompt前缀: "${state.prompt.substring(0, 50)}..."`);
        
        if (state.$wrap.data('generating')) {
            addLog('GEN_SKIP', `Block ${state.blockIdx}: 已有生图任务进行中，跳过`);
            return;
        }
        state.$wrap.data('generating', true);
        addLog('GEN_LOCK', `Block ${state.blockIdx}: 已设置生成锁，防止重复触发`);
        
        const p = state.prompt;
        const prefix = settings.globalPrefix ? settings.globalPrefix + ', ' : '';
        const suffix = settings.globalSuffix ? ', ' + settings.globalSuffix : '';
        let finalPrompt = (prefix + p + suffix).replace(/,\s*,/g, ',').trim();
        addLog('GEN_PROMPT', `Block ${state.blockIdx}: 最终Prompt长度=${finalPrompt.length}, 负面词=${settings.globalNegative ? '已设置' : '未设置'}`);
        
        let cmd = `/sd quiet=true ${settings.globalNegative ? `negative="${escapeArg(settings.globalNegative)}"` : ''} ${finalPrompt}`;
        addLog('GEN_CMD', `Block ${state.blockIdx}: 命令已构造 - 长度=${cmd.length}`);
        
        const showMsg = (txt) => {
            state.el.msg.text(txt).addClass('show');
            setTimeout(() => state.el.msg.removeClass('show'), 2000);
        };

        showMsg('⏳ 请求中...');
        addLog('GEN_UI', `Block ${state.blockIdx}: UI状态更新 - 显示"请求中"`);
        state.el.img.css('opacity', '0.5');

        try {
            addLog('GEN_API', `Block ${state.blockIdx}: 正在调用 triggerSlash API...`);
            const result = await triggerSlash(cmd);
            addLog('GEN_RESULT', `Block ${state.blockIdx}: API返回结果长度=${result ? result.length : 0}`);
            
            const newUrls = (result || '').match(/(https?:\/\/|\/|output\/)[^\s"']+\.(png|jpg|jpeg|webp|gif)/gi) || [];
            addLog('GEN_PARSE', `Block ${state.blockIdx}: 解析到 ${newUrls.length} 个图片URL`);
            
            if (newUrls.length > 0) {
                addLog('SUCCESS', `Block ${state.blockIdx}: 成功生成图片 - URLs: ${newUrls.join(', ')}`);
                showMsg('✅ 成功');
                newUrls.forEach(u => state.images.push(u));
                const uniqueImages = [...new Set(state.images)];
                addLog('GEN_SAVE', `Block ${state.blockIdx}: 图片数组更新 - 去重后共 ${uniqueImages.length} 张`);
                
                await updateChatData(state.mesId, state.blockIdx, state.prompt, uniqueImages, false);
                updateWrapperView(state.$wrap, uniqueImages, uniqueImages.length - 1);
                addLog('GEN_COMPLETE', `Block ${state.blockIdx}: 生图流程完成，UI已更新`);
            } else {
                addLog('WARN', `Block ${state.blockIdx}: API响应中未找到图片URL`);
                showMsg('⚠️ 无结果');
            }
        } catch (err) {
            addLog('ERROR', `Block ${state.blockIdx}: 生图失败 - ${err.message}`);
            showMsg('❌ 错误');
        } finally {
            state.$wrap.data('generating', false);
            state.el.img.css('opacity', '1');
            addLog('GEN_UNLOCK', `Block ${state.blockIdx}: 已解除生成锁`);
        }
    }

    function updateWrapperView($wrap, images, idx) {
        const count = images.length;
        if (idx >= count) idx = count - 1;
        if (idx < 0) idx = 0;

        $wrap.attr('data-cur-idx', idx);
        $wrap.attr('data-images', encodeURIComponent(JSON.stringify(images)));

        const $img = $wrap.find('.sd-ui-image');
        const $ph = $wrap.find('.sd-placeholder');
        const $right = $wrap.find('.sd-zone.right');
        const $left = $wrap.find('.sd-zone.left');
        const $del = $wrap.find('.sd-zone.delete');
        const $msg = $wrap.find('.sd-ui-msg');

        if (count === 0) {
            $img.hide(); 
            $ph.show();
            $right.addClass('gen-mode').attr('title', '点击生成图片');
            $left.hide(); 
            $del.hide();
        } else {
            $ph.hide();
            $img.attr('src', images[idx]).show();
            $left.toggle(idx > 0);
            $del.show();
            if (idx === count - 1) $right.addClass('gen-mode').attr('title', '生成新图');
            else $right.removeClass('gen-mode').attr('title', '下一张');
            
            $msg.text(`${idx + 1} / ${count}`).addClass('show');
            setTimeout(() => $msg.removeClass('show'), 2000);
        }
    }

    async function updateChatData(mesId, blockIndex, prompt, images, preventAuto) {
        const index = parseInt(mesId);
        const chat = SillyTavern.chat;
        if (!chat || !chat[index]) return;

        const innerContent = rebuildBlockString(prompt, images, preventAuto);
        const newBlock = settings.startTag + '\n' + innerContent + '\n' + settings.endTag;

        const sTag = escapeRegExp(settings.startTag);
        const eTag = escapeRegExp(settings.endTag);
        const regex = new RegExp(`${sTag}([\\s\\S]*?)${eTag}`, 'g');
        
        let content = chat[index].mes;
        const matches = [...content.matchAll(regex)];
        
        if (matches.length > blockIndex) {
            const targetMatch = matches[blockIndex];
            const startIndex = targetMatch.index;
            const endIndex = startIndex + targetMatch[0].length;
            const newContent = content.substring(0, startIndex) + newBlock + content.substring(endIndex);
            
            await safeUpdateChat(index, newContent);
            addLog('SAVE', `Saved block index ${blockIndex} to message ${index}`);
        }
    }

    // ✅ 新增：带持续监听的处理函数（5次间隔2s）
    function processChatDOMWithPersistentListening() {
        addLog('EVENT', `[监听触发] 开始处理聊天DOM (第 ${persistentListenCount + 1} 次)`);
        processChatDOM();
        
        // 持续监听5次，每次间隔2秒
        if (persistentListenCount < 4) {
            persistentListenCount++;
            setTimeout(() => {
                addLog('EVENT', `[持续监听] 第 ${persistentListenCount + 1} 次延迟处理`);
                processChatDOM();
                processChatDOMWithPersistentListening();
            }, 2000);
        } else {
            persistentListenCount = 0;
            addLog('EVENT', '[监听结束] 完成5次持续监听');
        }
    }

    // ✅ 辅助函数：从 $wrap 构造 state 对象
    function buildStateFromWrap($wrap) {
        const $mes = $wrap.closest('.mes');
        const mesId = $mes.attr('mesid');
        if (!mesId) {
            addLog('ERROR', 'buildStateFromWrap: 无法获取 mesId，跳过');
            return null;
        }

        const blockIdx = parseInt($wrap.attr('data-block-idx'));
        const imgCount = JSON.parse(decodeURIComponent($wrap.attr('data-images'))).length;
        const prevent = $wrap.attr('data-prevent-auto') === 'true';
        
        addLog('STATE_BUILD', `Block ${blockIdx}: 构造 state 对象 - mesId=${mesId}, 图片数=${imgCount}, preventAuto=${prevent}`);

        return {
            $wrap,
            mesId,
            prompt: decodeURIComponent($wrap.attr('data-prompt')),
            images: JSON.parse(decodeURIComponent($wrap.attr('data-images'))),
            preventAuto: prevent,
            blockIdx: blockIdx,
            el: {
                img: $wrap.find('.sd-ui-image'),
                msg: $wrap.find('.sd-ui-msg'),
                viewport: $wrap.find('.sd-ui-viewport'),
                toggle: $wrap.find('.sd-ui-toggle')
            }
        };
    }

    function processChatDOM() {
        if (!settings.enabled) return;

        const sTag = settings.startTag;
        const eTag = settings.endTag;
        const pattern = `${escapeRegExp(sTag)}([\\s\\S]*?)${escapeRegExp(eTag)}`;
        const regex = new RegExp(pattern, 'g');

        $('.mes_text').each(function() {
            const $el = $(this);
            
            let blockIdx = 0;
            
            const hasTHRender = $el.find('.TH-render').length > 0;
            
            if (hasTHRender) {
                console.log('[SD] 检测到TH-render，使用精准替换模式');
                
                let processedCount = 0;
                
                $el.children().each(function() {
                    const $child = $(this);
                    
                    if ($child.hasClass('TH-render') || $child.find('.TH-render').length > 0) {
                        console.log('[SD] 跳过TH-render元素');
                        return;
                    }
                    
                    if ($child.find('.sd-ui-wrap').length > 0) {
                        return;
                    }
                    
                    const childHtml = $child.html();
                    
                    if (childHtml && childHtml.indexOf(sTag) !== -1) {
                        let hasChange = false;
                        
                        const newHtml = childHtml.replace(regex, (match, content) => {
                            hasChange = true;
                            const currentIdx = blockIdx++;
                            const parsed = parseBlockContent(content);
                            const initIdx = Math.max(0, parsed.images.length - 1);
                            return createUIHtml(parsed.prompt, parsed.images, parsed.preventAuto, currentIdx, initIdx);
                        });
                        
                        if (hasChange) {
                            $child.html(newHtml);
                            processedCount++;
                            console.log('[SD] 已处理子元素:', $child[0].tagName, '块索引:', blockIdx - 1);
                            
                            setTimeout(() => {
                                $child.find('.sd-ui-msg.show').removeClass('show');
                                
                                // ✅ 改为直接调用 handleGeneration，不再模拟点击
                                $child.find('.sd-ui-wrap').each(function() {
                                    const $w = $(this);
                                    const prevent = $w.attr('data-prevent-auto') === 'true';
                                    const imgs = JSON.parse(decodeURIComponent($w.attr('data-images')));
                                    const currentBlockIdx = parseInt($w.attr('data-block-idx'));
                                    
                                    addLog('AUTO_CHECK', `Block ${currentBlockIdx}: 检查自动生图条件 - 图片数=${imgs.length}, preventAuto=${prevent}`);
                                    
                                    if (imgs.length === 0 && !prevent) {
                                        const delay = 500 + (currentBlockIdx * 1000);
                                        addLog('AUTO_SCHEDULE', `Block ${currentBlockIdx}: 满足自动生图条件，将在 ${delay}ms 后触发`);
                                        
                                        setTimeout(() => {
                                            addLog('AUTO_TRIGGER', `Block ${currentBlockIdx}: 延迟时间到，开始构造 state 并调用生图函数`);
                                            const state = buildStateFromWrap($w);
                                            if (state) {
                                                addLog('AUTO_GEN', `Block ${state.blockIdx}: 直接调用 handleGeneration()`);
                                                handleGeneration(state);
                                            } else {
                                                addLog('AUTO_FAIL', `Block ${currentBlockIdx}: state 构造失败，无法触发自动生图`);
                                            }
                                        }, delay);
                                    } else {
                                        if (imgs.length > 0) {
                                            addLog('AUTO_SKIP', `Block ${currentBlockIdx}: 已有 ${imgs.length} 张图片，跳过自动生图`);
                                        }
                                        if (prevent) {
                                            addLog('AUTO_SKIP', `Block ${currentBlockIdx}: preventAuto=true，跳过自动生图`);
                                        }
                                    }
                                });
                            }, 100);
                        }
                    }
                });
                
                if (processedCount > 0) {
                    console.log(`[SD] 精准替换完成，处理了 ${processedCount} 个元素，共 ${blockIdx} 个块`);
                }
                
                return;
            }
            
            const html = $el.html();
            if (html.indexOf(sTag) === -1) return;
            if ($el.find('.sd-ui-wrap').length > 0 && !$el.attr('data-dirty')) return;

            let hasChange = false;
            
            const newHtml = html.replace(regex, (match, content) => {
                hasChange = true;
                const currentIdx = blockIdx++;
                const parsed = parseBlockContent(content);
                const initIdx = Math.max(0, parsed.images.length - 1);
                return createUIHtml(parsed.prompt, parsed.images, parsed.preventAuto, currentIdx, initIdx);
            });

            if (hasChange) {
                $el.html(newHtml);
                
                setTimeout(() => $el.find('.sd-ui-msg.show').removeClass('show'), 2000);
                
                // ✅ 改为直接调用 handleGeneration，不再模拟点击
                $el.find('.sd-ui-wrap').each(function() {
                    const $w = $(this);
                    const prevent = $w.attr('data-prevent-auto') === 'true';
                    const imgs = JSON.parse(decodeURIComponent($w.attr('data-images')));
                    const currentBlockIdx = parseInt($w.attr('data-block-idx'));
                    
                    addLog('AUTO_CHECK', `Block ${currentBlockIdx}: 检查自动生图条件 - 图片数=${imgs.length}, preventAuto=${prevent}`);
                    
                    if (imgs.length === 0 && !prevent) {
                        const delay = 500 + (blockIdx * 1000);
                        addLog('AUTO_SCHEDULE', `Block ${currentBlockIdx}: 满足自动生图条件，将在 ${delay}ms 后触发`);
                        
                        setTimeout(() => {
                            addLog('AUTO_TRIGGER', `Block ${currentBlockIdx}: 延迟时间到，开始构造 state 并调用生图函数`);
                            const state = buildStateFromWrap($w);
                            if (state) {
                                addLog('AUTO_GEN', `Block ${state.blockIdx}: 直接调用 handleGeneration()`);
                                handleGeneration(state);
                            } else {
                                addLog('AUTO_FAIL', `Block ${currentBlockIdx}: state 构造失败，无法触发自动生图`);
                            }
                        }, delay);
                    } else {
                        if (imgs.length > 0) {
                            addLog('AUTO_SKIP', `Block ${currentBlockIdx}: 已有 ${imgs.length} 张图片，跳过自动生图`);
                        }
                        if (prevent) {
                            addLog('AUTO_SKIP', `Block ${currentBlockIdx}: preventAuto=true，跳过自动生图`);
                        }
                    }
                });
            }
        });
    }

    function parseBlockContent(rawContent) {
        const tempDiv = document.createElement('div');
        tempDiv.innerHTML = rawContent;
        let text = tempDiv.innerText || tempDiv.textContent || '';
        const preventAuto = rawContent.includes(NO_GEN_FLAG);
        const urlRegex = /(https?:\/\/|\/|output\/)[^\s"']+\.(png|jpg|jpeg|webp|gif)/gi;
        const images = text.match(urlRegex) || [];
        let prompt = text.replace(urlRegex, '').trim();
        prompt = prompt.replace(NO_GEN_FLAG, '').trim();
        prompt = prompt.replace(/^\s*[\r\n]/gm, '').trim();
        return { prompt, images, preventAuto };
    }

    function rebuildBlockString(prompt, images, preventAuto) {
        let content = prompt;
        if (images.length > 0) content += '\n' + images.join('\n');
        else if (preventAuto) content += '\n' + NO_GEN_FLAG;
        return content;
    }

    function createUIHtml(prompt, images, preventAuto, blockIdx, initIdx) {
        const safePrompt = encodeURIComponent(prompt);
        const safeImages = encodeURIComponent(JSON.stringify(images));
        const hasImages = images.length > 0;
        const currentImg = hasImages ? images[initIdx] : '';
        const currentCountText = hasImages ? `${initIdx + 1} / ${images.length}` : '';

        return `
        <div class="sd-ui-container">
            <div class="sd-ui-wrap" 
                 data-prompt="${safePrompt}" 
                 data-images="${safeImages}" 
                 data-prevent-auto="${preventAuto}"
                 data-block-idx="${blockIdx}"
                 data-cur-idx="${initIdx}">
                <div class="sd-ui-toggle" title="折叠/展开">▵</div>
                <div class="sd-ui-viewport">
                    <div class="sd-zone top" title="编辑提示词"></div>
                    <div class="sd-zone left" title="上一张" style="display:${initIdx > 0 ? 'block' : 'none'}"></div>
                    <div class="sd-zone right ${hasImages && initIdx === images.length-1 ? 'gen-mode' : ''} ${!hasImages ? 'gen-mode' : ''}" 
                         title="${hasImages && initIdx < images.length-1 ? '下一张' : '生成新图'}"></div>
                    <div class="sd-zone delete" title="删除当前图" style="display:${hasImages ? 'block' : 'none'}"></div>
                    <div class="sd-ui-msg ${hasImages ? 'show' : ''}">${currentCountText}</div>
                    <img class="sd-ui-image" src="${currentImg}" style="display:${hasImages ? 'block' : 'none'}" />
                    <div class="sd-placeholder" style="display:${hasImages ? 'none' : 'block'}">
                        <i class="fa-solid fa-image"></i> 等待生成...<br>
                        <small>（索引: ${blockIdx}）</small>
                    </div>
                </div>
            </div>
        </div>`;
    }

    function escapeArg(s) { return String(s || '').replace(/["\\]/g, '\\$&'); }
    function escapeRegExp(string) { return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

    // --- Menus & Popups ---
    function addMenuItem() {
        const extensionsMenu = $('#extensionsMenu');
        const menuItemId = `${SCRIPT_ID}-menu`;
        if (extensionsMenu.length === 0) { setTimeout(addMenuItem, 1000); return; }
        if ($(`#${menuItemId}`).length > 0) return;
        const menuItemHTML = `
            <div class="list-group-item flex-container flexGap5 interactable" id="${menuItemId}" title="设置SD生图助手">
                <div class="fa-fw fa-solid fa-paintbrush extensionsMenuExtensionButton"></div>
                <span>生图助手</span>
            </div>`;
        const $menuItem = $(menuItemHTML);
        $menuItem.on('click', (e) => { e.stopPropagation(); openSettingsPopup(); });
        extensionsMenu.append($menuItem);
    }

    function openEditPopup(state) {
        const timestamp = Date.now();
        const taId = `sd-edit-${timestamp}`; 
        const btnModId = `sd-mod-${timestamp}`; 
        const btnGenId = `sd-gen-${timestamp}`;
        const btnAiToggleId = `sd-ai-toggle-${timestamp}`;
        const aiBoxId = `sd-ai-box-${timestamp}`;
        const aiInputId = `sd-ai-input-${timestamp}`;
        const btnAiRunId = `sd-ai-run-${timestamp}`;

        const html = `
            <div style="padding:10px;">
                <h3>编辑提示词 (Block ${state.blockIdx})</h3>
                <textarea id="${taId}" class="text_pole" rows="5" style="width:100%; font-family:monospace; margin-bottom:10px;">${state.prompt}</textarea>
                
                <div id="${aiBoxId}" class="sd-ai-update-box">
                    <label style="font-size:0.9em; font-weight:bold;">AI修改指令 (Instruction):</label>
                    <textarea id="${aiInputId}" class="text_pole" rows="2" placeholder="例如：把衣服改成红色，增加下雨背景..." style="width:100%; margin:5px 0;"></textarea>
                    <div style="text-align:center; margin-top:5px;">
                        <button id="${btnAiRunId}" class="menu_button" style="font-size:0.9em; width:100%;">🚀 执行更新</button>
                    </div>
                </div>

                <div style="display:flex; gap:10px; margin-top:10px;">
                    <button id="${btnAiToggleId}" class="menu_button" style="flex:1;" title="AI 辅助修改">🪄 AI优化</button>
                    <button id="${btnModId}" class="menu_button" style="flex:1;">仅修改</button>
                    <button id="${btnGenId}" class="menu_button" style="flex:1; background:var(--SmartThemeQuoteColor); color:#fff;">生成</button>
                </div>
            </div>`;
            
        SillyTavern.callGenericPopup(html, 1, '', { wide: false });
        
        setTimeout(() => {
            const $promptArea = $(`#${taId}`);
            const $aiBox = $(`#${aiBoxId}`);
            
            $(`#${btnAiToggleId}`).on('click', () => $aiBox.toggleClass('show'));

            $(`#${btnAiRunId}`).on('click', async function() {
                const instruction = $(`#${aiInputId}`).val().trim();
                if(!instruction) { toastr.warning('请输入指令'); return; }
                const btn = $(this);
                const originalText = btn.text();
                btn.prop('disabled', true).text('🤖 处理中...');
                try {
                    const currentPrompt = $promptArea.val();
                    const newPrompt = await callLLMForUpdate(currentPrompt, instruction);
                    $promptArea.val(newPrompt);
                    toastr.success('AI更新成功');
                    $aiBox.removeClass('show');
                } catch(e) { toastr.error(e.message); }
                finally { btn.prop('disabled', false).text(originalText); }
            });

            $(`#${btnModId}`).on('click', async function() {
                state.prompt = $promptArea.val().trim();
                state.$wrap.attr('data-prompt', encodeURIComponent(state.prompt));
                closeCurrentPopup(this);
                await updateChatData(state.mesId, state.blockIdx, state.prompt, state.images, state.preventAuto);
            });
            
            $(`#${btnGenId}`).on('click', async function() {
                state.prompt = $promptArea.val().trim();
                state.$wrap.attr('data-prompt', encodeURIComponent(state.prompt));
                closeCurrentPopup(this);
                await updateChatData(state.mesId, state.blockIdx, state.prompt, state.images, state.preventAuto);
                state.prompt = $promptArea.val().trim();
                addLog('POPUP_GEN', `Block ${state.blockIdx}: 用户通过编辑弹窗触发生图`);
                handleGeneration(state);
            });
        }, 100);
    }

    function closeCurrentPopup(triggerBtn) {
        try {
            const $btn = $(triggerBtn);
            const $popup = $btn.closest('.popup, .popup-body, dialog');
            if ($popup.length) {
                const $okBtn = $popup.find('.popup-button-ok');
                if ($okBtn.length && $okBtn.is(':visible')) { $okBtn.trigger('click'); return; }
            }
            const $lastOk = $('.popup-button-ok:visible').last();
            if ($lastOk.length) $lastOk.trigger('click');
            else if (typeof SillyTavern !== 'undefined' && SillyTavern.closePopup) SillyTavern.closePopup();
            else $('#genericPopupClose').click();
        } catch (e) { console.error('[SD] Close popup failed', e); }
    }

    function openSettingsPopup() {
        const timestamp = Date.now();
        const btnSaveId = `sd-save-${timestamp}`; const tabInjId = `sd-tab-inj-${timestamp}`; const tabCfgId = `sd-tab-cfg-${timestamp}`; const tabApiId = `sd-tab-api-${timestamp}`; const tabLogId = `sd-tab-log-${timestamp}`;
        const btnResetId = `sd-reset-${timestamp}`;
        const contentInjId = `sd-content-inj-${timestamp}`; const contentCfgId = `sd-content-cfg-${timestamp}`; const contentApiId = `sd-content-api-${timestamp}`; const contentLogId = `sd-content-log-${timestamp}`;
        const btnExpId = `sd-export-${timestamp}`; const btnImpId = `sd-import-${timestamp}`;
        const logText = RUNTIME_LOGS.join('\n');

        const popupHtml = `
            <div style="padding: 10px; max-height: 70vh; overflow-y: auto; overflow-x: hidden; scrollbar-width: thin;">
                <h3 style="margin-bottom: 15px;">🎨 SD生图助手 v30</h3>
                <div class="sd-tab-nav">
                    <div id="${tabInjId}" class="sd-tab-btn active">注入(Prompt)</div>
                    <div id="${tabCfgId}" class="sd-tab-btn">基础设置</div>
                    <div id="${tabApiId}" class="sd-tab-btn">API设置</div>
                    <div id="${tabLogId}" class="sd-tab-btn">日志</div>
                </div>
                <div id="${contentInjId}" class="sd-tab-content active">
                    <div style="margin-bottom:15px; padding:10px; background:rgba(0,0,0,0.1); border-radius:5px;">
                        <label class="checkbox_label" style="display: flex; align-items: center; margin-bottom:10px;">
                            <input type="checkbox" id="sd-inject-enable" ${settings.injectEnabled ? 'checked' : ''} /> 
                            <span style="margin-left: 8px; font-weight:bold;">启用提示词注入 (Context Injection)</span>
                        </label>
                        <label class="checkbox_label" style="display: flex; align-items: center; margin-bottom:10px;">
                            <input type="checkbox" id="sd-ai-tmpl-enable" ${settings.aiUpdateWithTemplate ? 'checked' : ''} /> 
                            <span style="margin-left: 8px;">AI修图时携带完整模版 (Include Template in AI Update)</span>
                        </label>
                        <div style="display:flex; gap:15px; margin-top:10px;">
                            <div style="flex:1"><label>插入深度 (0=最后):</label><input type="number" id="sd-inject-depth" class="text_pole" value="${settings.injectDepth}" min="0" max="50" style="width:100%" /></div>
                            <div style="flex:1">
                                <label>发送身份 (Role):</label>
                                <select id="sd-inject-role" class="text_pole" style="width:100%">
                                    <option value="system" ${settings.injectRole === 'system' ? 'selected' : ''}>System (系统)</option>
                                    <option value="user" ${settings.injectRole === 'user' ? 'selected' : ''}>User (用户)</option>
                                    <option value="assistant" ${settings.injectRole === 'assistant' ? 'selected' : ''}>Assistant (AI)</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div style="margin-bottom:15px; text-align:right;"><small style="color:#aaa; cursor:pointer;" id="sd-mode-toggle">[切换模式: ${settings.useRawMode ? '原始文本' : '角色构造器'}]</small></div>
                    <div id="sd-mode-builder" style="display:${settings.useRawMode ? 'none' : 'block'}">
                        <h4 style="margin-bottom:10px; border-bottom:1px solid #555; padding-bottom:5px;">角色特征数据库 (Character DB)</h4>
                        <div id="sd-char-list-container"></div>
                        <button id="sd-add-char" class="sd-add-btn">+ 添加角色 (Add Character)</button>
                        <div class="sd-accordion" id="sd-tpl-top-header"><span>前置模版 (Template Top)</span> <span>▿</span></div>
                        <div class="sd-accordion-content" id="sd-tpl-top-content"><textarea id="sd-tpl-top" class="text_pole" rows="6" style="width:100%; font-family:monospace; font-size:0.8em;">${settings.templateTop}</textarea></div>
                        <div class="sd-accordion" id="sd-tpl-bot-header"><span>后置模版 (Template Bottom)</span> <span>▿</span></div>
                        <div class="sd-accordion-content" id="sd-tpl-bot-content"><textarea id="sd-tpl-bot" class="text_pole" rows="6" style="width:100%; font-family:monospace; font-size:0.8em;">${settings.templateBottom}</textarea></div>
                    </div>
                    <div id="sd-mode-raw" style="display:${settings.useRawMode ? 'block' : 'none'}">
                        <label>完整注入文本 (Raw Prompt):</label>
                        <textarea id="sd-inject-prompt-raw" class="text_pole" rows="15" style="width:100%; font-family:monospace">${settings.injectPrompt}</textarea>
                    </div>
                </div>
                <div id="${contentCfgId}" class="sd-tab-content">
                    <label class="checkbox_label" style="margin-bottom: 15px; display: flex; align-items: center;"><input type="checkbox" id="sd-enable-toggle" ${settings.enabled ? 'checked' : ''} /> <span style="margin-left: 8px;">启用生图解析功能 (Image Parsing)</span></label>
                    <div style="margin-bottom: 10px;"><label>全局前缀 (Prefix):</label><textarea id="sd-prefix" class="text_pole" rows="2" style="width:100%; font-family:monospace">${settings.globalPrefix}</textarea></div>
                    <div style="margin-bottom: 10px;"><label>全局后缀 (Suffix):</label><textarea id="sd-suffix" class="text_pole" rows="2" style="width:100%; font-family:monospace">${settings.globalSuffix}</textarea></div>
                    <div style="margin-bottom: 15px;"><label>全局负面 (Negative):</label><textarea id="sd-negative" class="text_pole" rows="3" style="width:100%; font-family:monospace">${settings.globalNegative}</textarea></div>
                    <div style="margin-top:20px; border-top:1px solid #555; padding-top:15px;">
                        <label style="font-weight:bold;">配置同步 (Configuration Sync):</label>
                        <div style="display:flex; gap:10px; margin-top:10px;">
                            <button id="${btnExpId}" class="menu_button" style="flex:1;">📤 导出配置 (Export)</button>
                            <button id="${btnImpId}" class="menu_button" style="flex:1;">📥 导入配置 (Import)</button>
                        </div>
                    </div>
                </div>
                <div id="${contentApiId}" class="sd-tab-content">
                    <div class="sd-placeholder" style="margin-bottom:15px; text-align:left; padding:10px;">在此配置兼容 OpenAI 格式的 API以支持"AI更新"功能。</div>
                    <div style="margin-bottom: 10px;"><label>API基础URL (Base URL):</label><input type="text" id="sd-api-url" class="text_pole" style="width:100%" value="${settings.llmConfig.baseUrl}" placeholder="http://127.0.0.1:7861/v1" /></div>
                    <div style="margin-bottom: 10px;"><label>API密钥 (API Key):</label><input type="password" id="sd-api-key" class="text_pole" style="width:100%" value="${settings.llmConfig.apiKey}" placeholder="sk-..." /></div>
                    <div style="display:flex; gap:10px; margin-bottom:10px; align-items:flex-end;">
                        <div style="flex:1"><label>选择模型:</label><select id="sd-api-model" class="text_pole" style="width:100%"><option value="${settings.llmConfig.model}">${settings.llmConfig.model || '未选择'}</option></select></div>
                        <button id="sd-api-load-btn" class="menu_button" style="width:100px; height:38px;">连接加载</button>
                    </div>
                    <div style="display:flex; gap:10px;">
                         <div style="flex:1"><label>最大Tokens (生成长度):</label><input type="number" id="sd-api-tokens" class="text_pole" value="${settings.llmConfig.maxTokens}" style="width:100%" placeholder="4096" /></div>
                        <div style="flex:1"><label>温度 (Temperature):</label><input type="number" id="sd-api-temp" class="text_pole" value="${settings.llmConfig.temperature}" step="0.1" max="2.0" style="width:100%" /></div>
                    </div>
                </div>
                <div id="${contentLogId}" class="sd-tab-content"><textarea readonly class="text_pole" style="width:100%; height:300px; font-family:monospace; font-size:0.8em; white-space:pre;">${logText}</textarea></div>
                <button id="${btnResetId}" class="menu_button" style="width: 100%; padding: 10px; background-color: #666; color: #fff; margin-top: 5px;">
                    <i class="fa-solid fa-rotate-left"></i> 重置为默认设置
                </button>
                <button id="${btnSaveId}" class="menu_button" style="width: 100%; padding: 10px; background-color: var(--SmartThemeQuoteColor); color: #fff; margin-top: 10px;">
                    <i class="fa-solid fa-save"></i> 保存设置
                </button>
            </div>`;
            
        SillyTavern.callGenericPopup(popupHtml, 1, '', { wide: false });
        
        setTimeout(() => {
            const switchTab = (activeTab, activeContent) => {
                $(`#${tabCfgId}, #${tabInjId}, #${tabLogId}, #${tabApiId}`).removeClass('active');
                $(`#${contentCfgId}, #${contentInjId}, #${contentLogId}, #${contentApiId}`).removeClass('active');
                activeTab.addClass('active'); activeContent.addClass('active');
            };
            $(`#${tabCfgId}`).on('click', () => switchTab($(`#${tabCfgId}`), $(`#${contentCfgId}`)));
            $(`#${tabInjId}`).on('click', () => switchTab($(`#${tabInjId}`), $(`#${contentInjId}`)));
            $(`#${tabLogId}`).on('click', () => switchTab($(`#${tabLogId}`), $(`#${contentLogId}`)));
            $(`#${tabApiId}`).on('click', () => switchTab($(`#${tabApiId}`), $(`#${contentApiId}`)));

            const $charContainer = $('#sd-char-list-container');
            const renderCharRow = (name, tags, enabled) => {
                const $row = $(`<div class="sd-char-row"><input type="checkbox" class="sd-char-enable" ${enabled?'checked':''} style="margin-top:10px; margin-right:5px; cursor:pointer;" title="是否启用此角色" /><input type="text" class="text_pole sd-char-name" placeholder="角色名" value="${name}" /><textarea class="text_pole sd-char-tags" rows="2" placeholder="固定特征 (Fixed Tags)">${tags}</textarea><button class="sd-char-del" title="删除">✕</button></div>`);
                $row.find('.sd-char-del').on('click', () => $row.remove());
                $charContainer.append($row);
            };
            if (settings.characters && settings.characters.length > 0) settings.characters.forEach(c => renderCharRow(c.name, c.tags, c.enabled !== false));
            else renderCharRow('', '', true);
            $('#sd-add-char').on('click', () => renderCharRow('', '', true));

            const toggleAccord = (headerId, contentId) => {
                $(`#${headerId}`).on('click', () => {
                    $(`#${contentId}`).toggleClass('show');
                    $(`#${headerId} span:last-child`).text($(`#${contentId}`).hasClass('show') ? '▵' : '▿');
                });
            };
            toggleAccord('sd-tpl-top-header', 'sd-tpl-top-content');
            toggleAccord('sd-tpl-bot-header', 'sd-tpl-bot-content');

            $('#sd-mode-toggle').on('click', () => {
                settings.useRawMode = !settings.useRawMode;
                $('#sd-mode-builder').toggle(!settings.useRawMode);
                $('#sd-mode-raw').toggle(settings.useRawMode);
                $('#sd-mode-toggle').text(`[切换模式: ${settings.useRawMode ? '原始文本' : '角色构造器'}]`);
            });

            $(`#${btnExpId}`).on('click', function() {
                 const html = `<div style="padding:10px;"><h3>导出配置 (Export)</h3><textarea class="text_pole" rows="10" style="width:100%; font-family:monospace; font-size:0.8em;">${JSON.stringify(settings, null, 2)}</textarea></div>`;
                 SillyTavern.callGenericPopup(html, 1, '', { wide: false });
            });
            $(`#${btnImpId}`).on('click', function() {
                 const taId = `sd-imp-ta-${Date.now()}`; const confirmId = `sd-imp-confirm-${Date.now()}`;
                 const html = `<div style="padding:10px;"><h3>导入配置 (Import)</h3><textarea id="${taId}" class="text_pole" rows="10" style="width:100%; font-family:monospace; font-size:0.8em;"></textarea><button id="${confirmId}" class="menu_button" style="width:100%; margin-top:10px; background:var(--SmartThemeQuoteColor); color:#fff;">确认导入</button></div>`;
                 SillyTavern.callGenericPopup(html, 1, '', { wide: false });
                 setTimeout(() => {
                     $(`#${confirmId}`).on('click', () => {
                         try { settings = { ...DEFAULT_SETTINGS, ...JSON.parse($(`#${taId}`).val()) }; saveSettings(); toastr.success('配置导入成功！'); closeCurrentPopup(this); } 
                         catch(e) { toastr.error('解析错误: ' + e.message); }
                     });
                 }, 100);
            });

            $('#sd-api-load-btn').on('click', async function() {
                 const btn = $(this); const url = $('#sd-api-url').val().trim(); const key = $('#sd-api-key').val().trim();
                 if(!url) { toastr.warning('请输入基础URL'); return; }
                 btn.prop('disabled', true).text('加载中...');
                 try { 
                     const models = await fetchModels(url, key);
                     const $sel = $('#sd-api-model').empty();
                     if(Array.isArray(models)) models.forEach(m => $sel.append(`<option value="${m.id||m.model_name||m}">${m.id||m.model_name||m}</option>`));
                     toastr.success('模型列表加载成功');
                 } catch(e) { toastr.error('加载失败: ' + e.message); }
                 finally { btn.prop('disabled', false).text('连接加载'); }
            });

            $(`#${btnSaveId}`).on('click', function() {
                settings.enabled = $('#sd-enable-toggle').is(':checked');
                settings.globalPrefix = $('#sd-prefix').val(); settings.globalSuffix = $('#sd-suffix').val(); settings.globalNegative = $('#sd-negative').val();
                settings.injectEnabled = $('#sd-inject-enable').is(':checked'); settings.injectDepth = parseInt($('#sd-inject-depth').val()) || 0; settings.injectRole = $('#sd-inject-role').val(); settings.aiUpdateWithTemplate = $('#sd-ai-tmpl-enable').is(':checked'); 
                settings.llmConfig.baseUrl = $('#sd-api-url').val().trim(); settings.llmConfig.apiKey = $('#sd-api-key').val().trim(); settings.llmConfig.model = $('#sd-api-model').val(); settings.llmConfig.maxTokens = parseInt($('#sd-api-tokens').val()) || 500; settings.llmConfig.temperature = parseFloat($('#sd-api-temp').val()) || 0.7;
                if (settings.useRawMode) settings.injectPrompt = $('#sd-inject-prompt-raw').val();
                else {
                    const chars = []; $('.sd-char-row').each(function() { const n=$(this).find('.sd-char-name').val().trim(),t=$(this).find('.sd-char-tags').val().trim(),e=$(this).find('.sd-char-enable').is(':checked'); if(n)chars.push({name:n,tags:t,enabled:e}); });
                    settings.templateTop = $('#sd-tpl-top').val(); settings.templateBottom = $('#sd-tpl-bot').val(); settings.characters = chars;
                    settings.injectPrompt = `${settings.templateTop}\n${chars.filter(c=>c.enabled).map(c=>`* **${c.name}**: ${c.tags}`).join('\n')}\n${settings.templateBottom}`;
                    $('#sd-inject-prompt-raw').val(settings.injectPrompt);
                }
                saveSettings(); toastr.success('设置已保存'); closeCurrentPopup(this); processChatDOM();
            });

            $(`#${btnResetId}`).on('click', function () {
                if (!confirm('确定要重置为默认设置吗？这会覆盖当前所有配置。')) return;

                settings = {
                    ...DEFAULT_SETTINGS,
                    llmConfig: { ...DEFAULT_SETTINGS.llmConfig }
                };

                localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));

                if (typeof toastr !== 'undefined') {
                    toastr.success('已重置为默认设置，请关闭并重新打开设置窗口查看。');
                } else {
                    alert('已重置为默认设置，请关闭并重新打开设置窗口查看。');
                }

                try {
                    $('#genericPopupClose, .popup-button-ok').last().trigger('click');
                } catch (e) {}
            });
        }, 100);
    }

    async function triggerSlash(cmd) {
        const trigger = (window.triggerSlash || window.parent?.triggerSlash || window.parent?.TavernHelper?.triggerSlash);
        if (!trigger) throw new Error('API不可用');
        return await trigger.call(window.parent || window, cmd);
    }

    function handleContextInjection(data) {
        if (!settings.enabled || !settings.injectEnabled) return;
        let contextArray = Array.isArray(data) ? data : (data && Array.isArray(data.chat) ? data.chat : null);
        if (!contextArray && data && typeof data === 'object') {
             for (const key in data) if (Array.isArray(data[key]) && data[key].length > 0 && (data[key][0].role || data[key][0].name)) { contextArray = data[key]; break; }
        }
        if (!contextArray || !settings.injectPrompt) return;
        if (contextArray.some(msg => (msg.content === settings.injectPrompt) || (msg.mes === settings.injectPrompt))) return;
        const depth = Math.max(0, parseInt(settings.injectDepth) || 0);
        let targetIdx = contextArray.length - depth; if (targetIdx < 0) targetIdx = 0;
        contextArray.splice(targetIdx, 0, { role: settings.injectRole || 'system', content: settings.injectPrompt });
        addLog('INJECT', `Inserted prompt at index ${targetIdx}`);
    }

    function registerSTEvents() {
        if (!SillyTavern.eventSource) {
            addLog('ERROR', 'SillyTavern.eventSource 不可用');
            return;
        }

        // 注入上下文
        try { 
            SillyTavern.eventSource.on('chat_completion_prompt_ready', handleContextInjection); 
            addLog('EVENT', '✅ 已注册事件: chat_completion_prompt_ready');
        } catch(e) {
            addLog('ERROR', `注册 chat_completion_prompt_ready 失败: ${e.message}`);
        }

        const debouncedProcess = () => {
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(() => {
                persistentListenCount = 0;
                processChatDOMWithPersistentListening();
            }, 500);
        };

        const eventTypes = SillyTavern.eventTypes || {};
        
        if (eventTypes.USER_MESSAGE_RENDERED || 'user_message_rendered') {
            const eventName = eventTypes.USER_MESSAGE_RENDERED || 'user_message_rendered';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [USER_MESSAGE_RENDERED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.CHARACTER_MESSAGE_RENDERED || 'character_message_rendered') {
            const eventName = eventTypes.CHARACTER_MESSAGE_RENDERED || 'character_message_rendered';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [CHARACTER_MESSAGE_RENDERED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.CHAT_CHANGED || 'chat_changed') {
            const eventName = eventTypes.CHAT_CHANGED || 'chat_changed';
            SillyTavern.eventSource.on(eventName, (chatFilename) => {
                addLog('EVENT', `✅ [CHAT_CHANGED] 触发 - 聊天文件: ${chatFilename}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.MESSAGE_UPDATED || 'message_updated') {
            const eventName = eventTypes.MESSAGE_UPDATED || 'message_updated';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [MESSAGE_UPDATED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.MESSAGE_SWIPED || 'message_swiped') {
            const eventName = eventTypes.MESSAGE_SWIPED || 'message_swiped';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [MESSAGE_SWIPED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.GENERATION_ENDED || 'generation_ended') {
            const eventName = eventTypes.GENERATION_ENDED || 'generation_ended';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [GENERATION_ENDED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        if (eventTypes.MESSAGE_RECEIVED || 'message_received') {
            const eventName = eventTypes.MESSAGE_RECEIVED || 'message_received';
            SillyTavern.eventSource.on(eventName, (messageId) => {
                addLog('EVENT', `✅ [MESSAGE_RECEIVED] 触发 - 消息ID: ${messageId}`);
                debouncedProcess();
            });
            addLog('EVENT', `✅ 已注册事件: ${eventName}`);
        }

        addLog('EVENT', '✅ 所有酒馆事件监听已注册完成');
    }
})();
